//! SGD against Adam on the same problem, same budget, same initialisation.
//!
//! Run:
//!   cargo run -p aether-gpu --example train_optimizers --release
//!
//! # Why the learning-rate sweep
//!
//! Adam and SGD have different natural step sizes -- Adam normalises by the
//! second moment, so its useful range sits one to two orders of magnitude below
//! SGD's. Running both at one shared rate does not compare optimisers, it
//! compares one optimiser against the other one held at a rate it was never
//! meant to use, and whichever rate is chosen decides the winner in advance.
//!
//! Each optimiser therefore gets the same small sweep over its own range and is
//! reported at its best. The sweep is part of the result, not a detail: the
//! comparison is "best of four rates each", and the per-rate numbers are printed
//! so a reader can see how sensitive each one was rather than taking the maximum
//! on trust.
//!
//! # What this does not establish
//!
//! One synthetic task, one architecture, one epoch budget, one seed per fold.
//! Nothing here generalises to other problems. It is an end-to-end exercise of
//! the Adam kernels against a known-good SGD path, with a number attached.

use std::time::Instant;

use aether_gpu::datasets;
use aether_gpu::{AdamState, GpuContext, GpuTensor};

const FOLDS: usize = 5;
const EPOCHS: usize = 100;
const HIDDEN: usize = 64;
const CLASSES: usize = 3;
const PER_CLASS: usize = 300;

const SGD_RATES: [f32; 4] = [0.1, 0.25, 0.5, 1.0];
const ADAM_RATES: [f32; 4] = [0.001, 0.005, 0.01, 0.05];

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Opt {
    Sgd,
    Adam,
}

/// Draws arc positions uniformly at random rather than walking them in order.
///
/// This is what makes an independently generated set a genuine i.i.d. sample
/// from the same distribution. Evenly spaced positions are not a sample; they
/// are a deterministic sweep, and two sweeps with the same spacing differ only
/// by their noise, which is why splitting one sweep cannot produce a test set
/// that is both unseen and in-distribution.
///
/// Delegates to `datasets::spirals_iid`, which this used to reimplement line for
/// line -- same radius, same 2.2*pi sweep, same 0.30 and 0.12 jitter, same LCG
/// constants. Two copies of a generator are two tasks waiting to diverge, and
/// the cost of that is not hypothetical: `train_mlp_cv` differed from this one
/// only in its sweep and jitter and reported an accuracy 0.14 lower, a gap that
/// read as a property of the optimiser until the generators were compared. The
/// wrapper is kept for the arity the rest of this file calls with.
fn spirals_iid(seed: u64, per_class: usize) -> (Vec<f32>, Vec<usize>) {
    datasets::spirals_iid(seed, CLASSES, per_class)
}

fn spirals(seed: u64) -> (Vec<f32>, Vec<usize>) {
    let mut rng = datasets::Lcg::new(seed);
    let mut x = Vec::new();
    let mut y = Vec::new();
    for class in 0..CLASSES {
        for i in 0..PER_CLASS {
            let t = i as f32 / PER_CLASS as f32;
            let radius = 0.15 + 3.85 * t;
            let angle = 2.2 * core::f32::consts::PI * t
                + class as f32 * 2.0 * core::f32::consts::PI / CLASSES as f32;
            let jr = (rng.next_f32() - 0.5) * 0.30;
            let ja = (rng.next_f32() - 0.5) * 0.12;
            x.push((radius + jr) * (angle + ja).cos() / 4.0);
            x.push((radius + jr) * (angle + ja).sin() / 4.0);
            y.push(class);
        }
    }
    (x, y)
}

/// Round-robin stratification: deal each class's points across folds one at a
/// time. Class balance is exact.
///
/// **This split does not measure generalisation on this data.** The spirals are
/// generated by walking an arc in order, so consecutive points sit a fraction of
/// the arc apart, and dealing them alternately puts a near-duplicate of every
/// held-out point into the training set. Measured: the median held-out point is
/// 0.99x the cloud's own nearest-neighbour spacing from its nearest training
/// point, so the split separates nothing.
///
/// Kept because it is the split the earlier examples in this crate used, and
/// the comparison against the blocked split below is the evidence for why it
/// should not be.
#[allow(dead_code)]
fn interleaved_folds(y: &[usize], folds: usize) -> Vec<usize> {
    let mut assignment = vec![0usize; y.len()];
    let mut next = vec![0usize; CLASSES];
    for (i, &class) in y.iter().enumerate() {
        assignment[i] = next[class] % folds;
        next[class] += 1;
    }
    assignment
}

/// Blocked stratification: each class's points are cut into contiguous arcs and
/// each arc becomes one fold.
///
/// Class balance is still exact, but a held-out point is now adjacent to
/// training data only at the two ends of its arc. The interior of each block is
/// genuinely unseen, so accuracy measures whether the model learned the shape
/// rather than whether it can interpolate between neighbours.
fn blocked_folds(y: &[usize], folds: usize) -> Vec<usize> {
    let mut assignment = vec![0usize; y.len()];
    let mut seen = vec![0usize; CLASSES];
    let per_class = y.len() / CLASSES;
    let block = per_class / folds;

    for (i, &class) in y.iter().enumerate() {
        let idx_in_class = seen[class];
        assignment[i] = (idx_in_class / block).min(folds - 1);
        seen[class] += 1;
    }
    assignment
}

fn one_hot(y: &[usize]) -> Vec<f32> {
    let mut out = vec![0.0f32; y.len() * CLASSES];
    for (i, &c) in y.iter().enumerate() {
        out[i * CLASSES + c] = 1.0;
    }
    out
}

fn init_weights(fan_in: usize, fan_out: usize, rng: &mut datasets::Lcg) -> Vec<f32> {
    let bound = (6.0f32 / fan_in as f32).sqrt();
    (0..fan_in * fan_out)
        .map(|_| (rng.next_f32() * 2.0 - 1.0) * bound)
        .collect()
}

/// Parameters plus, for Adam, the moment state that has to persist across
/// steps. `None` for SGD, which is stateless.
struct Params {
    t: Vec<GpuTensor>,
    adam: Option<Vec<AdamState>>,
}

impl Params {
    fn new(ctx: &GpuContext, rng: &mut datasets::Lcg, opt: Opt) -> Self {
        let up = |v: Vec<f32>, r, c| ctx.upload(&v, r, c).expect("upload");
        let t = vec![
            up(init_weights(2, HIDDEN, rng), 2, HIDDEN),
            up(vec![0.0; HIDDEN], 1, HIDDEN),
            up(init_weights(HIDDEN, HIDDEN, rng), HIDDEN, HIDDEN),
            up(vec![0.0; HIDDEN], 1, HIDDEN),
            up(init_weights(HIDDEN, CLASSES, rng), HIDDEN, CLASSES),
            up(vec![0.0; CLASSES], 1, CLASSES),
        ];
        let adam = if opt == Opt::Adam {
            Some(
                t.iter()
                    .map(|p| ctx.adam_state(p).expect("state"))
                    .collect(),
            )
        } else {
            None
        };
        Self { t, adam }
    }

    /// Throw away Adam's moments and step counter, keeping the parameters.
    ///
    /// This is what resuming a run does. `AdamState` keeps its moments private,
    /// so a process that stops and restarts cannot carry them across and calls
    /// `adam_state` again, which zeroes both and resets the counter. Doing it
    /// mid-run here measures the cost of that without needing two processes.
    fn rebuild_adam_state(&mut self, ctx: &GpuContext) {
        if self.adam.is_some() {
            self.adam = Some(
                self.t
                    .iter()
                    .map(|p| ctx.adam_state(p).expect("state"))
                    .collect(),
            );
        }
    }

    fn apply(&mut self, ctx: &GpuContext, grads: Vec<GpuTensor>, lr: f32) {
        for (i, g) in grads.into_iter().enumerate() {
            self.t[i] = match &mut self.adam {
                Some(states) => ctx
                    .adam_update_resident(&self.t[i], &g, &mut states[i], lr)
                    .expect("adam"),
                None => ctx.sgd_update_resident(&self.t[i], &g, lr).expect("sgd"),
            };
        }
    }
}

fn forward(
    ctx: &GpuContext,
    p: &Params,
    x: &GpuTensor,
) -> (GpuTensor, GpuTensor, GpuTensor, GpuTensor, GpuTensor) {
    let z1 = ctx.matmul_resident(x, &p.t[0]).expect("z1");
    let z1 = ctx.add_bias_resident(&z1, &p.t[1]).expect("z1b");
    let a1 = ctx.relu_resident(&z1).expect("a1");
    let z2 = ctx.matmul_resident(&a1, &p.t[2]).expect("z2");
    let z2 = ctx.add_bias_resident(&z2, &p.t[3]).expect("z2b");
    let a2 = ctx.relu_resident(&z2).expect("a2");
    let z3 = ctx.matmul_resident(&a2, &p.t[4]).expect("z3");
    let z3 = ctx.add_bias_resident(&z3, &p.t[5]).expect("z3b");
    (z1, a1, z2, a2, z3)
}

fn step(ctx: &GpuContext, p: &mut Params, x: &GpuTensor, y: &GpuTensor, lr: f32) {
    let (z1, a1, z2, a2, z3) = forward(ctx, p, x);

    let dz3 = ctx.softmax_xent_grad_resident(&z3, y).expect("dz3");
    let a2t = ctx.transpose_resident(&a2).expect("a2t");
    let dw3 = ctx.matmul_resident(&a2t, &dz3).expect("dw3");
    let db3 = ctx.column_sums_resident(&dz3).expect("db3");

    let w3t = ctx.transpose_resident(&p.t[4]).expect("w3t");
    let da2 = ctx.matmul_resident(&dz3, &w3t).expect("da2");
    let dz2 = ctx.relu_backward_resident(&z2, &da2).expect("dz2");

    let a1t = ctx.transpose_resident(&a1).expect("a1t");
    let dw2 = ctx.matmul_resident(&a1t, &dz2).expect("dw2");
    let db2 = ctx.column_sums_resident(&dz2).expect("db2");

    let w2t = ctx.transpose_resident(&p.t[2]).expect("w2t");
    let da1 = ctx.matmul_resident(&dz2, &w2t).expect("da1");
    let dz1 = ctx.relu_backward_resident(&z1, &da1).expect("dz1");

    let xt = ctx.transpose_resident(x).expect("xt");
    let dw1 = ctx.matmul_resident(&xt, &dz1).expect("dw1");
    let db1 = ctx.column_sums_resident(&dz1).expect("db1");

    p.apply(ctx, vec![dw1, db1, dw2, db2, dw3, db3], lr);
    ctx.flush();
}

fn predict(ctx: &GpuContext, p: &Params, x: &GpuTensor, rows: usize) -> Vec<usize> {
    let (_, _, _, _, z3) = forward(ctx, p, x);
    let probs = ctx
        .read(&ctx.softmax_resident(&z3).expect("softmax"))
        .expect("read");
    (0..rows)
        .map(|r| {
            let row = &probs[r * CLASSES..(r + 1) * CLASSES];
            let mut best = 0;
            for j in 1..CLASSES {
                if row[j] > row[best] {
                    best = j;
                }
            }
            best
        })
        .collect()
}

/// Train on one i.i.d. sample, evaluate on an independently drawn one.
///
/// This is the measurement the two cross-validation splits cannot provide. The
/// interleaved split puts a near-duplicate of every held-out point into
/// training, so it reports interpolation; the blocked split holds out whole arc
/// regions the model never sees, so it reports extrapolation. Neither is
/// generalisation on this data, because the data is a one-dimensional manifold
/// sampled in order and no partition of one ordered sweep is an i.i.d. split.
///
/// Two independent draws from the same generator are.
fn holdout_accuracy(
    ctx: &GpuContext,
    train_x: &[f32],
    train_hot: &[f32],
    n_tr: usize,
    test_x: &[f32],
    test_y: &[usize],
    opt: Opt,
    lr: f32,
    seed: u64,
    rebuild_adam_at: Option<usize>,
    epochs: usize,
) -> f32 {
    let gx = ctx.upload(train_x, n_tr, 2).expect("x");
    let gy = ctx.upload(train_hot, n_tr, CLASSES).expect("y");
    let gte = ctx.upload(test_x, test_y.len(), 2).expect("test x");

    let mut rng = datasets::Lcg::new(seed);
    let mut p = Params::new(ctx, &mut rng, opt);
    for epoch in 0..epochs {
        // A resume: the parameters survive, the optimiser's memory of them does
        // not. Placed before the step so the epoch it names is the first one
        // running on rebuilt state.
        if Some(epoch) == rebuild_adam_at {
            p.rebuild_adam_state(ctx);
        }
        step(ctx, &mut p, &gx, &gy, lr);
    }

    let pred = predict(ctx, &p, &gte, test_y.len());
    let correct = pred.iter().zip(test_y).filter(|(a, b)| a == b).count();
    correct as f32 / test_y.len() as f32
}

/// Mean cross-validated accuracy for one optimiser at one rate.
fn cross_validate(
    ctx: &GpuContext,
    x: &[f32],
    y: &[usize],
    folds: &[usize],
    y_hot: &[f32],
    opt: Opt,
    lr: f32,
) -> (f32, f32) {
    let n = y.len();
    let mut accs = Vec::with_capacity(FOLDS);

    for fold in 0..FOLDS {
        let (mut trx, mut tr_hot, mut tex, mut tey) = (vec![], vec![], vec![], vec![]);
        let mut n_tr = 0;
        for i in 0..n {
            if folds[i] == fold {
                tex.extend_from_slice(&x[i * 2..i * 2 + 2]);
                tey.push(y[i]);
            } else {
                trx.extend_from_slice(&x[i * 2..i * 2 + 2]);
                tr_hot.extend_from_slice(&y_hot[i * CLASSES..(i + 1) * CLASSES]);
                n_tr += 1;
            }
        }
        let n_te = tey.len();

        let gx = ctx.upload(&trx, n_tr, 2).expect("x");
        let gy = ctx.upload(&tr_hot, n_tr, CLASSES).expect("y");
        let gtex = ctx.upload(&tex, n_te, 2).expect("test x");

        // Same seed per fold across optimisers and rates, so the comparison
        // varies the optimiser and nothing else.
        let mut rng = datasets::Lcg::new(0xBEEF + fold as u64);
        let mut p = Params::new(ctx, &mut rng, opt);

        for _ in 0..EPOCHS {
            step(ctx, &mut p, &gx, &gy, lr);
        }

        let pred = predict(ctx, &p, &gtex, n_te);
        let correct = pred.iter().zip(&tey).filter(|(a, b)| a == b).count();
        accs.push(correct as f32 / n_te as f32);
    }

    let mean = accs.iter().sum::<f32>() / accs.len() as f32;
    let sd = (accs.iter().map(|a| (a - mean).powi(2)).sum::<f32>() / accs.len() as f32).sqrt();
    (mean, sd)
}

/// How far a held-out point is from the nearest point the model trained on.
///
/// Cross-validated accuracy only measures generalisation if the held-out points
/// are meaningfully different from the training ones. These spirals are
/// generated by walking an arc in order, and folds are assigned round-robin, so
/// consecutive points -- which sit a fraction of the arc apart -- land in
/// different folds. A model can then score well by interpolating between
/// near-duplicates rather than by learning the shape.
///
/// The number to compare against is the typical spacing of the cloud itself. If
/// test-to-train distance is not larger than that, the split is not separating
/// anything.
fn leakage_report(x: &[f32], folds: &[usize]) {
    let n = folds.len();
    let dist = |i: usize, j: usize| -> f32 {
        let dx = x[i * 2] - x[j * 2];
        let dy = x[i * 2 + 1] - x[j * 2 + 1];
        (dx * dx + dy * dy).sqrt()
    };

    // Nearest training point for each held-out point, fold 0 as the sample.
    let mut to_train: Vec<f32> = Vec::new();
    for i in 0..n {
        if folds[i] != 0 {
            continue;
        }
        let mut best = f32::INFINITY;
        for j in 0..n {
            if folds[j] != 0 {
                best = best.min(dist(i, j));
            }
        }
        to_train.push(best);
    }

    // Nearest other point overall, as the scale of the cloud.
    let mut overall: Vec<f32> = Vec::new();
    for i in 0..n {
        let mut best = f32::INFINITY;
        for j in 0..n {
            if i != j {
                best = best.min(dist(i, j));
            }
        }
        overall.push(best);
    }

    let median = |v: &mut Vec<f32>| -> f32 {
        v.sort_by(f32::total_cmp);
        v[v.len() / 2]
    };

    let m_train = median(&mut to_train);
    let m_overall = median(&mut overall);

    println!("═══════════════════════════════════════════════════════════════════");
    println!("  Split diagnostic");
    println!("═══════════════════════════════════════════════════════════════════");
    println!("  median distance, held-out point to nearest training point  {m_train:.5}");
    println!("  median nearest-neighbour distance in the full cloud        {m_overall:.5}");
    println!(
        "  ratio                                                      {:.2}x",
        m_train / m_overall
    );

    if m_train < 2.0 * m_overall {
        println!();
        println!("  Every held-out point has a training point essentially on top of");
        println!("  it. Accuracy here measures interpolation between near-duplicates,");
        println!("  not generalisation, and a score near 1.0 should be read that way.");
    }
    println!();
}

fn main() {
    let ctx = match GpuContext::new() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("No GPU adapter: {e}");
            std::process::exit(1);
        }
    };
    let info = ctx.adapter_info();
    if !info.is_hardware() {
        eprintln!("adapter is {}, refusing to report as GPU", info.device_type);
        std::process::exit(1);
    }

    let (x, y) = spirals(0x5B1FA1);
    let n = y.len();
    let y_hot = one_hot(&y);

    println!();
    println!("  interleaved split (what the earlier examples in this crate use):");
    leakage_report(&x, &interleaved_folds(&y, FOLDS));
    println!("  blocked split (used below):");
    let folds = blocked_folds(&y, FOLDS);

    let majority = {
        let mut counts = vec![0usize; CLASSES];
        for &c in &y {
            counts[c] += 1;
        }
        *counts.iter().max().unwrap() as f32 / n as f32
    };

    leakage_report(&x, &folds);

    println!("═══════════════════════════════════════════════════════════════════");
    println!("  SGD vs Adam, {FOLDS}-fold stratified CV, {EPOCHS} epochs, identical init");
    println!("═══════════════════════════════════════════════════════════════════");
    println!("  adapter    {}  |  {}", info.name, info.backend);
    println!("  data       {CLASSES} interleaved spirals, {n} points (synthetic)");
    println!("  network    2 -> {HIDDEN} -> {HIDDEN} -> {CLASSES}, ReLU, softmax + cross-entropy");
    println!();

    // The interleaved split is measured too, as the control for the claim that
    // it is not measuring generalisation.
    let interleaved = interleaved_folds(&y, FOLDS);
    let sgd_interleaved = SGD_RATES
        .iter()
        .map(|&lr| cross_validate(&ctx, &x, &y, &interleaved, &y_hot, Opt::Sgd, lr).0)
        .fold(0.0f32, f32::max);
    let adam_interleaved = ADAM_RATES
        .iter()
        .map(|&lr| cross_validate(&ctx, &x, &y, &interleaved, &y_hot, Opt::Adam, lr).0)
        .fold(0.0f32, f32::max);

    let start = Instant::now();
    let mut best: Vec<(Opt, f32, f32, f32)> = Vec::new();

    for (opt, rates) in [(Opt::Sgd, &SGD_RATES), (Opt::Adam, &ADAM_RATES)] {
        println!("  {opt:?}");
        println!("  {:>10}  {:>10}  {:>10}", "lr", "CV acc", "sd");
        let mut top = (f32::NAN, f32::NAN, f32::NAN);

        for &lr in rates.iter() {
            let (mean, sd) = cross_validate(&ctx, &x, &y, &folds, &y_hot, opt, lr);
            println!("  {lr:>10.4}  {mean:>10.4}  {sd:>10.4}");
            if top.1.is_nan() || mean > top.1 {
                top = (lr, mean, sd);
            }
        }

        best.push((opt, top.0, top.1, top.2));
        println!();
    }

    let elapsed = start.elapsed();

    println!("───────────────────────────────────────────────────────────────────");
    println!(
        "  {:>8}  {:>8}  {:>10}  {:>10}",
        "optimiser", "best lr", "CV acc", "sd"
    );
    for (opt, lr, mean, sd) in &best {
        println!("  {:>8?}  {lr:>8.4}  {mean:>10.4}  {sd:>10.4}", opt);
    }

    let sgd = best[0].2;
    let adam = best[1].2;

    // ── The measurement the CV splits cannot give ─────────────────────────────
    println!("───────────────────────────────────────────────────────────────────");
    println!("  Independent-sample holdout: train and test drawn separately");
    println!("  {:>10}  {:>10}  {:>12}", "optimiser", "lr", "holdout acc");

    let (tr_x, tr_y) = spirals_iid(0x11D_1, 300);
    let (te_x, te_y) = spirals_iid(0x11D_2, 300);
    let tr_hot = one_hot(&tr_y);
    let n_tr = tr_y.len();

    let mut holdout = Vec::new();
    for (opt, rates) in [(Opt::Sgd, &SGD_RATES), (Opt::Adam, &ADAM_RATES)] {
        let mut top: (f32, f32) = (f32::NAN, f32::NAN);
        for &lr in rates.iter() {
            let acc = holdout_accuracy(
                &ctx, &tr_x, &tr_hot, n_tr, &te_x, &te_y, opt, lr, 0xBEEF, None, EPOCHS,
            );
            println!("  {:>10?}  {lr:>10.4}  {acc:>12.4}", opt);
            if top.1.is_nan() || acc > top.1 {
                top = (lr, acc);
            }
        }
        holdout.push((opt, top.0, top.1));
    }

    // What a resumed run costs, on a task with a held-out set.
    //
    // `AdamState` keeps its moments private, so a process that stops and
    // restarts rebuilds them from zero. A unit test measures that the parameters
    // diverge; it cannot say whether the resumed run is *worse*, which needs a
    // task and something held out. This is that measurement: the same training,
    // the same seed, the same learning rate, with the optimiser's state discarded
    // halfway.
    if let Some(&(_, best_lr, _)) = holdout.iter().find(|(o, _, _)| *o == Opt::Adam) {
        println!();
        println!("  Adam with its state rebuilt mid-run, lr {best_lr:.4}");
        println!(
            "  {:>8}  {:>12}  {:>12}  {:>10}",
            "seed", "continuous", "resumed", "delta"
        );

        let mut deltas = Vec::new();
        for seed in [0xBEEFu64, 0xC0FFEE, 0xD00D, 0xFEED, 0xBEAD] {
            let whole = holdout_accuracy(
                &ctx,
                &tr_x,
                &tr_hot,
                n_tr,
                &te_x,
                &te_y,
                Opt::Adam,
                best_lr,
                seed,
                None,
                EPOCHS,
            );
            let resumed = holdout_accuracy(
                &ctx,
                &tr_x,
                &tr_hot,
                n_tr,
                &te_x,
                &te_y,
                Opt::Adam,
                best_lr,
                seed,
                Some(EPOCHS / 2),
                EPOCHS,
            );
            println!(
                "  {seed:>8x}  {whole:>12.4}  {resumed:>12.4}  {:>+10.4}",
                resumed - whole
            );
            deltas.push(resumed - whole);
        }

        // When the resume happens, not just that it does.
        //
        // This was added expecting early resumes to be the expensive ones: the
        // moments discarded then still carry information the parameters do not,
        // while a late resume perturbs a search that has mostly finished. The
        // measurement says the opposite, and the ordering is monotone rather than
        // noisy -- nothing at epochs 2 through 25, -0.0004 at 50, -0.0009 at 90.
        //
        // What the hypothesis left out is recovery. A resume at epoch 2 restarts
        // bias correction with 98 epochs left to re-converge, and the run arrives
        // where it would have anyway. At epoch 90 there are ten, and the large
        // effective steps that t = 1 produces move a converged solution with no
        // time to settle again. The cost is not what the moments knew; it is how
        // long the run has to recover from losing them.
        println!();
        println!("  the same comparison against when the state is discarded");
        println!(
            "  {:>10}  {:>14}  {:>14}",
            "resume at", "mean delta", "worst delta"
        );
        for at in [2usize, 5, 10, 25, 50, 90] {
            let mut d = Vec::new();
            for seed in [0xBEEFu64, 0xC0FFEE, 0xD00D, 0xFEED, 0xBEAD] {
                let whole = holdout_accuracy(
                    &ctx,
                    &tr_x,
                    &tr_hot,
                    n_tr,
                    &te_x,
                    &te_y,
                    Opt::Adam,
                    best_lr,
                    seed,
                    None,
                    EPOCHS,
                );
                let resumed = holdout_accuracy(
                    &ctx,
                    &tr_x,
                    &tr_hot,
                    n_tr,
                    &te_x,
                    &te_y,
                    Opt::Adam,
                    best_lr,
                    seed,
                    Some(at),
                    EPOCHS,
                );
                d.push(resumed - whole);
            }
            let mean = d.iter().sum::<f32>() / d.len() as f32;
            let worst = d
                .iter()
                .cloned()
                .fold(0.0f32, |a, v| if v < a { v } else { a });
            println!(
                "  {:>8}    {mean:>+14.4}  {worst:>+14.4}",
                format!("epoch {at}")
            );
        }

        // Which explanation the ordering supports.
        //
        // Late resumes cost more, and two stories fit: a late state is more
        // fragile, or a late resume simply leaves too few epochs to recover from
        // losing it. They differ in a testable way -- hold the resume epoch fixed
        // and give the run more training afterwards. Under recovery the cost goes
        // away; under fragility it does not.
        //
        // It goes away. Resuming at epoch 90 costs -0.0009 with ten epochs left
        // and exactly nothing with twenty-five or more. The state discarded is
        // identical in every row; only the time to re-converge differs, so the
        // cost is the missing recovery and not the lateness.
        //
        // Read the middle rows as counts, not as a curve. The held-out set is 900
        // points and the mean is over five seeds, so one flipped label moves it by
        // 1/900/5, about 0.00022. The deltas at 10, 13, 15 and 20 epochs are four,
        // one, four and three flipped labels; they do not decrease monotonically
        // because there is nothing between them to decrease through. What the
        // sweep locates is a transition between twenty and twenty-five epochs of
        // recovery, and the wobble below it is quantisation rather than structure.
        //
        // Which makes the practical reading narrow: discarding Adam's moments is
        // free whenever the run has room to settle again, and the case to avoid
        // is a resume near the end of a fixed budget.
        println!();
        println!("  resuming at epoch 90 with more training left afterwards");
        println!(
            "  {:>8}  {:>12}  {:>14}",
            "total", "left after", "mean delta"
        );
        for total in [100usize, 103, 105, 110, 115, 120, 150] {
            let mut d = Vec::new();
            for seed in [0xBEEFu64, 0xC0FFEE, 0xD00D, 0xFEED, 0xBEAD] {
                let whole = holdout_accuracy(
                    &ctx,
                    &tr_x,
                    &tr_hot,
                    n_tr,
                    &te_x,
                    &te_y,
                    Opt::Adam,
                    best_lr,
                    seed,
                    None,
                    total,
                );
                let resumed = holdout_accuracy(
                    &ctx,
                    &tr_x,
                    &tr_hot,
                    n_tr,
                    &te_x,
                    &te_y,
                    Opt::Adam,
                    best_lr,
                    seed,
                    Some(90),
                    total,
                );
                d.push(resumed - whole);
            }
            let mean = d.iter().sum::<f32>() / d.len() as f32;
            println!("  {total:>8}  {:>12}  {mean:>+14.4}", total - 90);
        }

        // Is twenty-five epochs a constant, or a fraction of the budget?
        //
        // The row above finds the cost gone with twenty-five epochs left, on a
        // hundred-epoch budget with the resume at ninety. Two readings fit: the
        // model needs about twenty-five epochs to re-converge whatever the
        // budget, or it needs about a quarter of one. Doubling the budget and
        // resuming at the same fraction separates them -- an absolute boundary
        // stays near twenty-five, a proportional one moves to about fifty.
        //
        // It stays. On two hundred epochs the cost is gone by twenty, the same
        // order as on one hundred, and nothing appears at fifty that was not
        // there at thirty. The -0.0004 at twenty-five is two flipped labels,
        // the same quantum as the sweep above and not a return of the effect.
        //
        // So the recovery Adam needs after losing its moments is a number of
        // epochs, not a share of the run. A checkpoint interval wants about
        // twenty-five epochs of headroom before the end whether the run is a
        // hundred epochs or a thousand.
        println!();
        println!("  the same boundary on a 200-epoch budget, resuming at 180");
        println!("  {:>12}  {:>14}", "left after", "mean delta");
        for total in [190usize, 200, 205, 210, 230] {
            let mut d = Vec::new();
            for seed in [0xBEEFu64, 0xC0FFEE, 0xD00D, 0xFEED, 0xBEAD] {
                let whole = holdout_accuracy(
                    &ctx,
                    &tr_x,
                    &tr_hot,
                    n_tr,
                    &te_x,
                    &te_y,
                    Opt::Adam,
                    best_lr,
                    seed,
                    None,
                    total,
                );
                let resumed = holdout_accuracy(
                    &ctx,
                    &tr_x,
                    &tr_hot,
                    n_tr,
                    &te_x,
                    &te_y,
                    Opt::Adam,
                    best_lr,
                    seed,
                    Some(180),
                    total,
                );
                d.push(resumed - whole);
            }
            let mean = d.iter().sum::<f32>() / d.len() as f32;
            println!("  {:>12}  {mean:>+14.4}", total - 180);
        }

        let mean = deltas.iter().sum::<f32>() / deltas.len() as f32;
        let worst = deltas.iter().cloned().fold(0.0f32, |a, d| a.max(d.abs()));
        println!("  mean delta {mean:+.4}, largest single move {worst:.4}");
        println!();
        println!("  A resume discards both moment estimates and the step counter, so");
        println!("  bias correction restarts at t = 1 while the parameters carry on.");
        println!("  Whether that costs accuracy is what these five rows answer; the");
        println!("  unit test alongside them only establishes that it changes them.");

        let saturated = deltas.len() - deltas.iter().filter(|d| d.abs() > f32::EPSILON).count();
        if saturated > 0 {
            println!();
            println!("  Read the ceiling before the delta. The continuous runs reach");
            println!("  1.0000 here, so there is no headroom for a resume to lose and");
            println!(
                "  {saturated} of {} seeds move by exactly zero. This measures",
                deltas.len()
            );
            println!("  that a resume costs nothing on a task the model already solves,");
            println!("  which is weaker than costing nothing. A task with a gap left to");
            println!("  close would be the one that could show a cost.");
        }
    }

    println!("───────────────────────────────────────────────────────────────────");
    println!("  Three measurements of the same models");
    println!();
    println!("  {:>28}  {:>8}  {:>8}", "", "SGD", "Adam");
    println!(
        "  {:>28}  {:>8.4}  {:>8.4}",
        "interleaved CV", sgd_interleaved, adam_interleaved
    );
    println!("  {:>28}  {:>8.4}  {:>8.4}", "blocked CV", sgd, adam);
    println!(
        "  {:>28}  {:>8.4}  {:>8.4}",
        "independent-sample holdout", holdout[0].2, holdout[1].2
    );
    println!(
        "  {:>28}  {:>8.4}  {:>8.4}",
        "majority-class control", majority, majority
    );
    println!();
    println!("  wall clock        {:.2} s", elapsed.as_secs_f64());
    println!("═══════════════════════════════════════════════════════════════════");
    println!("  The three rows disagree because two of them are not measuring");
    println!("  generalisation.");
    println!();
    println!("  Interleaved CV deals consecutive points along the arc into");
    println!("  different folds, so every held-out point has a training point");
    println!("  0.99x the cloud's own spacing away. It reports interpolation");
    println!("  between near-duplicates.");
    println!();
    println!("  Blocked CV holds out whole arc segments, so the model is asked");
    println!("  to extrapolate into regions it never saw. On interleaved");
    println!("  spirals that is not learnable from the other arcs, which is why");
    println!("  both optimisers land at or below the majority-class control.");
    println!();
    println!("  Neither is fixable by choosing a better partition, because the");
    println!("  data is a one-dimensional manifold swept in order and no");
    println!("  partition of one ordered sweep is an i.i.d. split. Drawing the");
    println!("  test set independently from the same generator is, and that row");
    println!("  is the one to read.");
    println!();
    println!("  One synthetic task, one architecture, one epoch budget, best of");
    println!("  four rates each. Nothing here transfers to other problems.");
    println!("═══════════════════════════════════════════════════════════════════");
}
